set define off
set sqlblanklines on

prompt Installing Task Center reference data

REM INSERTING into TSK_COMPLEXITIES
SET DEFINE OFF;
Insert into TSK_COMPLEXITIES (COMPLEXITY_ID,COMPLEXITY_CODE,COMPLEXITY_NAME,COMPLEXITY_WEIGHT,DISPLAY_SEQ,ACTIVE_YN) values (1,'LOW','Low',1,10,'Y');
Insert into TSK_COMPLEXITIES (COMPLEXITY_ID,COMPLEXITY_CODE,COMPLEXITY_NAME,COMPLEXITY_WEIGHT,DISPLAY_SEQ,ACTIVE_YN) values (2,'MEDIUM','Medium',2,20,'Y');
Insert into TSK_COMPLEXITIES (COMPLEXITY_ID,COMPLEXITY_CODE,COMPLEXITY_NAME,COMPLEXITY_WEIGHT,DISPLAY_SEQ,ACTIVE_YN) values (3,'HIGH','High',3,30,'Y');
Insert into TSK_COMPLEXITIES (COMPLEXITY_ID,COMPLEXITY_CODE,COMPLEXITY_NAME,COMPLEXITY_WEIGHT,DISPLAY_SEQ,ACTIVE_YN) values (4,'CRITICAL','Critical',5,40,'Y');
REM INSERTING into TSK_STATUSES
SET DEFINE OFF;
Insert into TSK_STATUSES (STATUS_ID,STATUS_CODE,STATUS_NAME,IS_OPEN_YN,IS_DONE_YN,DISPLAY_SEQ,ACTIVE_YN) values (6,'BACKLOG','Backlog','Y','N',5,'Y');
Insert into TSK_STATUSES (STATUS_ID,STATUS_CODE,STATUS_NAME,IS_OPEN_YN,IS_DONE_YN,DISPLAY_SEQ,ACTIVE_YN) values (1,'NOT_STARTED','Not Started','Y','N',10,'Y');
Insert into TSK_STATUSES (STATUS_ID,STATUS_CODE,STATUS_NAME,IS_OPEN_YN,IS_DONE_YN,DISPLAY_SEQ,ACTIVE_YN) values (2,'IN_PROGRESS','In Progress','Y','N',20,'Y');
Insert into TSK_STATUSES (STATUS_ID,STATUS_CODE,STATUS_NAME,IS_OPEN_YN,IS_DONE_YN,DISPLAY_SEQ,ACTIVE_YN) values (3,'IN_REVIEW','In Review','Y','N',30,'Y');
Insert into TSK_STATUSES (STATUS_ID,STATUS_CODE,STATUS_NAME,IS_OPEN_YN,IS_DONE_YN,DISPLAY_SEQ,ACTIVE_YN) values (4,'BLOCKED','Blocked','Y','N',40,'Y');
Insert into TSK_STATUSES (STATUS_ID,STATUS_CODE,STATUS_NAME,IS_OPEN_YN,IS_DONE_YN,DISPLAY_SEQ,ACTIVE_YN) values (5,'COMPLETED','Completed','N','Y',50,'Y');
Insert into TSK_STATUSES (STATUS_ID,STATUS_CODE,STATUS_NAME,IS_OPEN_YN,IS_DONE_YN,DISPLAY_SEQ,ACTIVE_YN) values (7,'ARCHIVE','Archive','N','Y',60,'Y');
REM INSERTING into TSK_TASK_TYPES
SET DEFINE OFF;
Insert into TSK_TASK_TYPES (TYPE_ID,TYPE_CODE,TYPE_NAME,DISPLAY_SEQ,ACTIVE_YN) values (1,'BUG','Bug',10,'Y');
Insert into TSK_TASK_TYPES (TYPE_ID,TYPE_CODE,TYPE_NAME,DISPLAY_SEQ,ACTIVE_YN) values (2,'NEW_FEATURE','New Feature',20,'Y');
Insert into TSK_TASK_TYPES (TYPE_ID,TYPE_CODE,TYPE_NAME,DISPLAY_SEQ,ACTIVE_YN) values (3,'ENHANCEMENT','Enhancement',30,'Y');
Insert into TSK_TASK_TYPES (TYPE_ID,TYPE_CODE,TYPE_NAME,DISPLAY_SEQ,ACTIVE_YN) values (4,'TASK','Task',40,'Y');
Insert into TSK_TASK_TYPES (TYPE_ID,TYPE_CODE,TYPE_NAME,DISPLAY_SEQ,ACTIVE_YN) values (5,'DOCUMENTATION','Documentation',50,'Y');
Insert into TSK_TASK_TYPES (TYPE_ID,TYPE_CODE,TYPE_NAME,DISPLAY_SEQ,ACTIVE_YN) values (6,'SUPPORT','Support',60,'Y');
Insert into TSK_TASK_TYPES (TYPE_ID,TYPE_CODE,TYPE_NAME,DISPLAY_SEQ,ACTIVE_YN) values (7,'UPLOAD_RECORDING','Upload Recording',70,'Y');

commit

prompt Task Center reference data installed
