set define off
set sqlblanklines on

prompt Installing Task Center schema objects


  CREATE OR REPLACE EDITIONABLE FUNCTION "TSK_APP_USER"
return varchar2
as
begin
    return coalesce(
        sys_context('APEX$SESSION', 'APP_USER'),
        sys_context('USERENV', 'SESSION_USER')
    );
end tsk_app_user;
/
/


  CREATE TABLE "TSK_USERS"
   (	"USER_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"USERNAME" VARCHAR2(100) NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(320) NOT NULL ENABLE,
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "TSK_USERS_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_USERS_U01" UNIQUE ("USERNAME")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_USERS_U02" UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TSK_TEAMS"
   (	"TEAM_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"TEAM_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"TEAM_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000),
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "TSK_TEAMS_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_TEAMS_PK" PRIMARY KEY ("TEAM_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TEAMS_U01" UNIQUE ("TEAM_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TSK_TEAM_MEMBERS"
   (	"TEAM_MEMBER_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"TEAM_ID" NUMBER NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"ROLE_NAME" VARCHAR2(100),
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"JOINED_ON" DATE DEFAULT trunc(sysdate) NOT NULL ENABLE,
	"LEFT_ON" DATE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "TSK_TEAM_MEMBERS_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_TEAM_MEMBERS_DATES_CK" CHECK (left_on is null or left_on >= joined_on) ENABLE,
	 CONSTRAINT "TSK_TEAM_MEMBERS_PK" PRIMARY KEY ("TEAM_MEMBER_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TEAM_MEMBERS_U01" UNIQUE ("TEAM_ID", "USER_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TEAM_MEMBERS_TEAM_FK" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "TSK_TEAMS" ("TEAM_ID") ENABLE,
	 CONSTRAINT "TSK_TEAM_MEMBERS_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "TSK_USERS" ("USER_ID") ENABLE
   ) ;


  CREATE TABLE "TSK_APPLICATIONS"
   (	"APPLICATION_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"APPLICATION_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"APPLICATION_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"OWNER_TEAM_ID" NUMBER,
	"DESCRIPTION" VARCHAR2(1000),
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "TSK_APPLICATIONS_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_APPLICATIONS_PK" PRIMARY KEY ("APPLICATION_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_APPLICATIONS_U01" UNIQUE ("APPLICATION_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_APPLICATIONS_TEAM_FK" FOREIGN KEY ("OWNER_TEAM_ID")
	  REFERENCES "TSK_TEAMS" ("TEAM_ID") ENABLE
   ) ;


  CREATE TABLE "TSK_COMPLEXITIES"
   (	"COMPLEXITY_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"COMPLEXITY_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"COMPLEXITY_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"COMPLEXITY_WEIGHT" NUMBER DEFAULT 1 NOT NULL ENABLE,
	"DISPLAY_SEQ" NUMBER DEFAULT 10 NOT NULL ENABLE,
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	 CONSTRAINT "TSK_COMPLEXITIES_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_COMPLEXITIES_WEIGHT_CK" CHECK (complexity_weight > 0) ENABLE,
	 CONSTRAINT "TSK_COMPLEXITIES_PK" PRIMARY KEY ("COMPLEXITY_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_COMPLEXITIES_U01" UNIQUE ("COMPLEXITY_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TSK_STATUSES"
   (	"STATUS_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"STATUS_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"STATUS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"IS_OPEN_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"IS_DONE_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"DISPLAY_SEQ" NUMBER DEFAULT 10 NOT NULL ENABLE,
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	 CONSTRAINT "TSK_STATUSES_OPEN_CK" CHECK (is_open_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_STATUSES_DONE_CK" CHECK (is_done_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_STATUSES_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_STATUSES_PK" PRIMARY KEY ("STATUS_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_STATUSES_U01" UNIQUE ("STATUS_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TSK_TASK_TYPES"
   (	"TYPE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"TYPE_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"TYPE_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"DISPLAY_SEQ" NUMBER DEFAULT 10 NOT NULL ENABLE,
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	 CONSTRAINT "TSK_TASK_TYPES_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_TASK_TYPES_PK" PRIMARY KEY ("TYPE_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TASK_TYPES_U01" UNIQUE ("TYPE_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TSK_TOPIC_GROUPS"
   (	"TOPIC_GROUP_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  CONSTRAINT "TSK_TOPIC_GROUPS_NN01" NOT NULL ENABLE,
	"TOPIC_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000),
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "TSK_TOPIC_GROUPS_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_TOPIC_GROUPS_PK" PRIMARY KEY ("TOPIC_GROUP_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TOPIC_GROUPS_U01" UNIQUE ("TOPIC_NAME")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TSK_TASKS"
   (	"TASK_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"TASK_KEY" VARCHAR2(30) GENERATED ALWAYS AS ('TASK-'||LPAD(TO_CHAR("TASK_ID"),6,'0')) VIRTUAL ,
	"TEAM_ID" NUMBER NOT NULL ENABLE,
	"TITLE" VARCHAR2(255) NOT NULL ENABLE,
	"DESCRIPTION" CLOB,
	"TYPE_ID" NUMBER NOT NULL ENABLE,
	"STATUS_ID" NUMBER,
	"COMPLEXITY_ID" NUMBER,
	"APPLICATION_ID" NUMBER,
	"OWNER_MEMBER_ID" NUMBER,
	"CREATED_BY_MEMBER_ID" NUMBER,
	"PRIORITY_CODE" VARCHAR2(30) DEFAULT 'MEDIUM' NOT NULL ENABLE,
	"START_DATE" DATE,
	"DUE_DATE" DATE,
	"COMPLETED_DATE" DATE,
	"ESTIMATED_HOURS" NUMBER(10,2),
	"ACTUAL_HOURS" NUMBER(10,2),
	"PERCENT_COMPLETE" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"EXTERNAL_REFERENCE" VARCHAR2(255),
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255),
	"TOPIC_GROUP_ID" NUMBER,
	 CONSTRAINT "TSK_TASKS_PRIORITY_CK" CHECK (priority_code in ('LOW','MEDIUM','HIGH','CRITICAL')) ENABLE,
	 CONSTRAINT "TSK_TASKS_PERCENT_CK" CHECK (percent_complete between 0 and 100) ENABLE,
	 CONSTRAINT "TSK_TASKS_HOURS_CK" CHECK (
            estimated_hours is null or estimated_hours >= 0
        ) ENABLE,
	 CONSTRAINT "TSK_TASKS_ACTUAL_HOURS_CK" CHECK (
            actual_hours is null or actual_hours >= 0
        ) ENABLE,
	 CONSTRAINT "TSK_TASKS_PK" PRIMARY KEY ("TASK_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TASKS_TEAM_FK" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "TSK_TEAMS" ("TEAM_ID") ENABLE,
	 CONSTRAINT "TSK_TASKS_TYPE_FK" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "TSK_TASK_TYPES" ("TYPE_ID") ENABLE,
	 CONSTRAINT "TSK_TASKS_STATUS_FK" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "TSK_STATUSES" ("STATUS_ID") ENABLE,
	 CONSTRAINT "TSK_TASKS_COMPLEXITY_FK" FOREIGN KEY ("COMPLEXITY_ID")
	  REFERENCES "TSK_COMPLEXITIES" ("COMPLEXITY_ID") ENABLE,
	 CONSTRAINT "TSK_TASKS_APPLICATION_FK" FOREIGN KEY ("APPLICATION_ID")
	  REFERENCES "TSK_APPLICATIONS" ("APPLICATION_ID") ENABLE,
	 CONSTRAINT "TSK_TASKS_OWNER_FK" FOREIGN KEY ("OWNER_MEMBER_ID")
	  REFERENCES "TSK_TEAM_MEMBERS" ("TEAM_MEMBER_ID") ENABLE,
	 CONSTRAINT "TSK_TASKS_CREATOR_FK" FOREIGN KEY ("CREATED_BY_MEMBER_ID")
	  REFERENCES "TSK_TEAM_MEMBERS" ("TEAM_MEMBER_ID") ENABLE,
	 CONSTRAINT "TSK_TASKS_TOPIC_GROUP_FK" FOREIGN KEY ("TOPIC_GROUP_ID")
	  REFERENCES "TSK_TOPIC_GROUPS" ("TOPIC_GROUP_ID") ENABLE
   ) ;


  CREATE TABLE "TSK_TASK_ASSIGNEES"
   (	"ASSIGNMENT_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"TASK_ID" NUMBER NOT NULL ENABLE,
	"TEAM_MEMBER_ID" NUMBER NOT NULL ENABLE,
	"ASSIGNMENT_ROLE" VARCHAR2(100),
	"ALLOCATED_PCT" NUMBER(3,0),
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"ASSIGNED_ON" DATE DEFAULT trunc(sysdate) NOT NULL ENABLE,
	"UNASSIGNED_ON" DATE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "TSK_TASK_ASSIGNEES_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_TASK_ASSIGNEES_ALLOC_CK" CHECK (allocated_pct is null or allocated_pct between 0 and 100) ENABLE,
	 CONSTRAINT "TSK_TASK_ASSIGNEES_DATES_CK" CHECK (unassigned_on is null or unassigned_on >= assigned_on) ENABLE,
	 CONSTRAINT "TSK_TASK_ASSIGNEES_PK" PRIMARY KEY ("ASSIGNMENT_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TASK_ASSIGNEES_TASK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "TSK_TASKS" ("TASK_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "TSK_TASK_ASSIGNEES_MEMBER_FK" FOREIGN KEY ("TEAM_MEMBER_ID")
	  REFERENCES "TSK_TEAM_MEMBERS" ("TEAM_MEMBER_ID") ENABLE
   ) ;


  CREATE TABLE "TSK_TASK_UPDATES"
   (	"UPDATE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"TASK_ID" NUMBER NOT NULL ENABLE,
	"TEAM_MEMBER_ID" NUMBER,
	"UPDATE_TYPE" VARCHAR2(30) DEFAULT 'COMMENT' NOT NULL ENABLE,
	"UPDATE_TEXT" CLOB NOT NULL ENABLE,
	"STATUS_ID" NUMBER,
	"PROGRESS_PCT" NUMBER(3,0),
	"HOURS_SPENT" NUMBER(10,2),
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	 CONSTRAINT "TSK_TASK_UPDATES_TYPE_CK" CHECK (update_type in ('COMMENT','STATUS','PROGRESS','BLOCKER','NOTE','SYSTEM')) ENABLE,
	 CONSTRAINT "TSK_TASK_UPDATES_PROGRESS_CK" CHECK (progress_pct is null or progress_pct between 0 and 100) ENABLE,
	 CONSTRAINT "TSK_TASK_UPDATES_HOURS_CK" CHECK (hours_spent is null or hours_spent >= 0) ENABLE,
	 CONSTRAINT "TSK_TASK_UPDATES_PK" PRIMARY KEY ("UPDATE_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TASK_UPDATES_TASK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "TSK_TASKS" ("TASK_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "TSK_TASK_UPDATES_MEMBER_FK" FOREIGN KEY ("TEAM_MEMBER_ID")
	  REFERENCES "TSK_TEAM_MEMBERS" ("TEAM_MEMBER_ID") ENABLE,
	 CONSTRAINT "TSK_TASK_UPDATES_STATUS_FK" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "TSK_STATUSES" ("STATUS_ID") ENABLE
   ) ;


  CREATE TABLE "TSK_TASK_FILES"
   (	"FILE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"TASK_ID" NUMBER NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(512) NOT NULL ENABLE,
	"MIME_TYPE" VARCHAR2(255),
	"FILE_CHARSET" VARCHAR2(128),
	"FILE_BLOB" BLOB NOT NULL ENABLE,
	"FILE_SIZE" NUMBER,
	"UPLOADED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPLOADED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255),
	"FILE_DISPLAY_NAME" VARCHAR2(255),
	"FILE_DESCRIPTION" VARCHAR2(4000),
	 CONSTRAINT "TSK_TASK_FILES_SIZE_CK" CHECK (file_size is null or file_size >= 0) ENABLE,
	 CONSTRAINT "TSK_TASK_FILES_PK" PRIMARY KEY ("FILE_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TASK_FILES_TASK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "TSK_TASKS" ("TASK_ID") ON DELETE CASCADE ENABLE
   ) ;


  CREATE TABLE "TSK_TASK_TOPIC_GROUPS"
   (	"TASK_TOPIC_GROUP_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  CONSTRAINT "TSK_TASK_TOPIC_GROUPS_NN01" NOT NULL ENABLE,
	"TASK_ID" NUMBER NOT NULL ENABLE,
	"TOPIC_GROUP_ID" NUMBER NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	 CONSTRAINT "TSK_TASK_TOPIC_GROUPS_PK" PRIMARY KEY ("TASK_TOPIC_GROUP_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TASK_TOPIC_GROUPS_U01" UNIQUE ("TASK_ID", "TOPIC_GROUP_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_TASK_TOPIC_GROUPS_TASK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "TSK_TASKS" ("TASK_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "TSK_TASK_TOPIC_GROUPS_TOPIC_FK" FOREIGN KEY ("TOPIC_GROUP_ID")
	  REFERENCES "TSK_TOPIC_GROUPS" ("TOPIC_GROUP_ID") ENABLE
   ) ;


  CREATE TABLE "TSK_CHANGE_LOG"
   (	"CHANGE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"ENTITY_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"ENTITY_PK" VARCHAR2(100),
	"TASK_ID" NUMBER,
	"CHANGE_ACTION" VARCHAR2(30) NOT NULL ENABLE,
	"FIELD_NAME" VARCHAR2(100),
	"OLD_VALUE" VARCHAR2(4000),
	"NEW_VALUE" VARCHAR2(4000),
	"CHANGE_NOTE" VARCHAR2(4000),
	"CHANGED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CHANGED_BY" VARCHAR2(255),
	 CONSTRAINT "TSK_CHANGE_LOG_ACTION_CK" CHECK (change_action in ('INSERT','UPDATE','DELETE','ASSIGN','UNASSIGN','COMMENT','REMOVE','REACTIVATE')) ENABLE,
	 CONSTRAINT "TSK_CHANGE_LOG_PK" PRIMARY KEY ("CHANGE_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TSK_EMAIL_SCHEDULES"
   (	"EMAIL_SCHEDULE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"TEAM_ID" NUMBER NOT NULL ENABLE,
	"SCHEDULE_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"SCHEDULE_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"ENABLED_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"SEND_HOUR" NUMBER(2,0) DEFAULT 8 NOT NULL ENABLE,
	"SEND_MINUTE" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"WEEKLY_DAY_NUMBER" NUMBER(1,0),
	"RECIPIENTS_SCOPE" VARCHAR2(50) DEFAULT 'TEAM_MEMBERS' NOT NULL ENABLE,
	"INCLUDE_ASSIGNED_TASKS_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"INCLUDE_TASK_UPDATES_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"INCLUDE_OVERDUE_TASKS_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"INCLUDE_COMMENTS_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255),
	"SEND_AT" TIMESTAMP (6),
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_ENABLED_CK" CHECK (enabled_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_HOUR_CK" CHECK (send_hour between 0 and 23) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_MINUTE_CK" CHECK (send_minute between 0 and 59) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_SCOPE_CK" CHECK (recipients_scope in ('TEAM_MEMBERS','TEAM_LEADS','MANAGERS','CUSTOM')) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_INC1_CK" CHECK (include_assigned_tasks_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_INC2_CK" CHECK (include_task_updates_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_INC3_CK" CHECK (include_overdue_tasks_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_INC4_CK" CHECK (include_comments_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_PK" PRIMARY KEY ("EMAIL_SCHEDULE_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_CODE_CK" CHECK (schedule_code in ('DAILY_MEMBER_STATUS','WEEKLY_TEAM_SUMMARY','MONTHLY_TEAM_PROGRESS')) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_DAY_CK" CHECK (
        weekly_day_number is null
        or (schedule_code = 'WEEKLY_TEAM_SUMMARY' and weekly_day_number between 1 and 7)
        or (schedule_code = 'MONTHLY_TEAM_PROGRESS' and weekly_day_number between 1 and 31)
    ) ENABLE,
	 CONSTRAINT "TSK_EMAIL_SCHEDULES_TEAM_FK" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "TSK_TEAMS" ("TEAM_ID") ENABLE
   ) ;


  CREATE TABLE "TSK_EMAIL_RECIPIENTS"
   (	"EMAIL_RECIPIENT_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"EMAIL_SCHEDULE_ID" NUMBER NOT NULL ENABLE,
	"TEAM_MEMBER_ID" NUMBER,
	"RECIPIENT_EMAIL" VARCHAR2(320),
	"ACTIVE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	 CONSTRAINT "TSK_EMAIL_RECIPIENTS_ACTIVE_CK" CHECK (active_yn in ('Y','N')) ENABLE,
	 CONSTRAINT "TSK_EMAIL_RECIPIENTS_TARGET_CK" CHECK (team_member_id is not null or recipient_email is not null) ENABLE,
	 CONSTRAINT "TSK_EMAIL_RECIPIENTS_PK" PRIMARY KEY ("EMAIL_RECIPIENT_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_EMAIL_RECIPIENTS_SCHED_FK" FOREIGN KEY ("EMAIL_SCHEDULE_ID")
	  REFERENCES "TSK_EMAIL_SCHEDULES" ("EMAIL_SCHEDULE_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "TSK_EMAIL_RECIPIENTS_MEMBER_FK" FOREIGN KEY ("TEAM_MEMBER_ID")
	  REFERENCES "TSK_TEAM_MEMBERS" ("TEAM_MEMBER_ID") ENABLE
   ) ;


  CREATE TABLE "TSK_EMAIL_LOG"
   (	"EMAIL_LOG_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"EMAIL_SCHEDULE_ID" NUMBER,
	"TEAM_ID" NUMBER,
	"TEAM_MEMBER_ID" NUMBER,
	"RECIPIENT_EMAIL" VARCHAR2(320),
	"EMAIL_SUBJECT" VARCHAR2(500),
	"EMAIL_BODY" CLOB,
	"STATUS_CODE" VARCHAR2(30) DEFAULT 'QUEUED' NOT NULL ENABLE,
	"RUN_PERIOD_START" DATE,
	"RUN_PERIOD_END" DATE,
	"QUEUED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE,
	"SENT_AT" TIMESTAMP (6),
	"ERROR_MESSAGE" CLOB,
	 CONSTRAINT "TSK_EMAIL_LOG_STATUS_CK" CHECK (status_code in ('QUEUED','SENT','FAILED','SKIPPED')) ENABLE,
	 CONSTRAINT "TSK_EMAIL_LOG_PK" PRIMARY KEY ("EMAIL_LOG_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "TSK_EMAIL_LOG_SCHEDULE_FK" FOREIGN KEY ("EMAIL_SCHEDULE_ID")
	  REFERENCES "TSK_EMAIL_SCHEDULES" ("EMAIL_SCHEDULE_ID") ENABLE,
	 CONSTRAINT "TSK_EMAIL_LOG_TEAM_FK" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "TSK_TEAMS" ("TEAM_ID") ENABLE,
	 CONSTRAINT "TSK_EMAIL_LOG_MEMBER_FK" FOREIGN KEY ("TEAM_MEMBER_ID")
	  REFERENCES "TSK_TEAM_MEMBERS" ("TEAM_MEMBER_ID") ENABLE
   ) ;


  CREATE INDEX "TSK_APPLICATIONS_I01" ON "TSK_APPLICATIONS" ("OWNER_TEAM_ID", "ACTIVE_YN")
  ;


  CREATE INDEX "TSK_CHANGE_LOG_I01" ON "TSK_CHANGE_LOG" ("TASK_ID", "CHANGED_AT")
  ;


  CREATE INDEX "TSK_CHANGE_LOG_I02" ON "TSK_CHANGE_LOG" ("ENTITY_NAME", "ENTITY_PK")
  ;


  CREATE INDEX "TSK_EMAIL_LOG_I01" ON "TSK_EMAIL_LOG" ("EMAIL_SCHEDULE_ID", "QUEUED_AT")
  ;


  CREATE INDEX "TSK_TASKS_I01" ON "TSK_TASKS" ("TEAM_ID", "STATUS_ID")
  ;


  CREATE INDEX "TSK_TASKS_I02" ON "TSK_TASKS" ("TEAM_ID", "DUE_DATE")
  ;


  CREATE INDEX "TSK_TASKS_I03" ON "TSK_TASKS" ("APPLICATION_ID")
  ;


  CREATE INDEX "TSK_TASKS_I04" ON "TSK_TASKS" ("TYPE_ID")
  ;


  CREATE INDEX "TSK_TASKS_I05" ON "TSK_TASKS" ("COMPLEXITY_ID")
  ;


  CREATE INDEX "TSK_TASKS_I06" ON "TSK_TASKS" ("TOPIC_GROUP_ID")
  ;


  CREATE UNIQUE INDEX "TSK_TASKS_U01" ON "TSK_TASKS" ("TASK_KEY")
  ;


  CREATE INDEX "TSK_TASK_ASSIGNEES_I01" ON "TSK_TASK_ASSIGNEES" ("TASK_ID")
  ;


  CREATE INDEX "TSK_TASK_ASSIGNEES_I02" ON "TSK_TASK_ASSIGNEES" ("TEAM_MEMBER_ID", "ACTIVE_YN")
  ;


  CREATE UNIQUE INDEX "TSK_TASK_ASSIGNEES_U01" ON "TSK_TASK_ASSIGNEES" (CASE "ACTIVE_YN" WHEN 'Y' THEN "TASK_ID" END , CASE "ACTIVE_YN" WHEN 'Y' THEN "TEAM_MEMBER_ID" END )
  ;


  CREATE INDEX "TSK_TASK_FILES_TASK_I" ON "TSK_TASK_FILES" ("TASK_ID")
  ;


  CREATE INDEX "TSK_TASK_TOPIC_GROUPS_I01" ON "TSK_TASK_TOPIC_GROUPS" ("TOPIC_GROUP_ID")
  ;


  CREATE INDEX "TSK_TASK_UPDATES_I01" ON "TSK_TASK_UPDATES" ("TASK_ID", "UPDATED_AT")
  ;


  CREATE INDEX "TSK_TASK_UPDATES_I02" ON "TSK_TASK_UPDATES" ("TEAM_MEMBER_ID", "UPDATED_AT")
  ;


  CREATE INDEX "TSK_TEAM_MEMBERS_I01" ON "TSK_TEAM_MEMBERS" ("TEAM_ID", "ACTIVE_YN")
  ;


  CREATE INDEX "TSK_TEAM_MEMBERS_I02" ON "TSK_TEAM_MEMBERS" ("USER_ID")
  ;


  CREATE OR REPLACE EDITIONABLE PACKAGE "TSK_DAILY_EMAIL_PKG" as
    function member_email_subject (
        p_team_member_id in number,
        p_run_date       in date default trunc(sysdate)
    ) return varchar2;

    function member_email_html (
        p_team_member_id in number,
        p_run_date       in date default trunc(sysdate)
    ) return clob;

    function monthly_team_subject (
        p_team_id  in number,
        p_run_date in date default trunc(sysdate)
    ) return varchar2;

    function monthly_team_html (
        p_team_id  in number,
        p_run_date in date default trunc(sysdate)
    ) return clob;

    function selected_schedule_is (
        p_email_schedule_id in number,
        p_schedule_code     in varchar2
    ) return boolean;

    procedure send_daily_summaries;
    procedure send_daily_schedule (
        p_email_schedule_id in number
    );
    procedure send_monthly_summaries;
    procedure sync_scheduler_jobs;
end tsk_daily_email_pkg;

/
/


  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "TSK_DAILY_EMAIL_PKG" as

    c_workspace constant varchar2(30) := 'DBAPPDEV';

    c_app_id    constant number := 12892;


    procedure set_apex_context is

    begin

        apex_util.set_security_group_id(

            apex_util.find_security_group_id(p_workspace => c_workspace)

        );

    end set_apex_context;


    function selected_schedule_is (

        p_email_schedule_id in number,

        p_schedule_code     in varchar2

    ) return boolean is

        l_count number;

    begin

        select count(*)

          into l_count

          from tsk_email_schedules

         where email_schedule_id = coalesce(

                   p_email_schedule_id,

                   (select min(email_schedule_id) from tsk_email_schedules)

               )

           and schedule_code = p_schedule_code;


        return l_count > 0;

    end selected_schedule_is;


    function task_url (

        p_task_id in number

    ) return varchar2 is

    begin

        return apex_mail.get_instance_url ||

               apex_page.get_url(

                   p_application => c_app_id,

                   p_page        => 12,

                   p_session     => 0,

                   p_clear_cache => '12',

                   p_items       => 'P12_TASK_ID',

                   p_values      => p_task_id,

                   p_plain_url   => true

               );

    end task_url;


    function html_href (

        p_url in varchar2

    ) return varchar2 is

    begin

        return replace(

                   replace(

                       replace(

                           replace(p_url, '&', '&amp;'),

                           '"', '&quot;'

                       ),

                       '<', '&lt;'

                   ),

                   '>', '&gt;'

               );

    end html_href;


    function member_email_subject (

        p_team_member_id in number,

        p_run_date       in date default trunc(sysdate)

    ) return varchar2 is

        l_display_name tsk_users.display_name%type;

    begin

        select u.display_name

          into l_display_name

          from tsk_team_members tm

          join tsk_users u

            on u.user_id = tm.user_id

         where tm.team_member_id = p_team_member_id;


        return 'Daily Task Summary for ' || l_display_name || ' - ' ||

               to_char(p_run_date, 'Mon DD, YYYY');

    exception

        when no_data_found then

            return 'Daily Task Summary - ' || to_char(p_run_date, 'Mon DD, YYYY');

    end member_email_subject;


    function member_email_html (

        p_team_member_id in number,

        p_run_date       in date default trunc(sysdate)

    ) return clob is

        l_html clob;

        l_summary tsk_v_daily_member_email%rowtype;

        l_has_due_tasks boolean := false;

        l_has_missing_due_tasks boolean := false;

    begin

        set_apex_context;


        select *

          into l_summary

          from tsk_v_daily_member_email

         where team_member_id = p_team_member_id;


        l_html :=

            '<div style="font-family:Arial,sans-serif;color:#172033;line-height:1.45">' ||

            '<h2 style="margin:0 0 4px">Daily Task Summary</h2>' ||

            '<div style="color:#5f6b7a;margin-bottom:18px">' ||

            apex_escape.html(l_summary.display_name) || ' &#8226; ' ||

            apex_escape.html(l_summary.team_name) || ' &#8226; ' ||

            to_char(p_run_date, 'Dy, Mon DD, YYYY') ||

            '</div>' ||

            '<table role="presentation" style="border-collapse:collapse;margin-bottom:18px;width:100%"><tr>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong>' || l_summary.open_tasks || '</strong><br>Open</td>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong>' || l_summary.in_progress_tasks || '</strong><br>In Progress</td>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong>' || l_summary.due_today_tasks || '</strong><br>Due Today</td>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong style="color:#b42318">' || l_summary.overdue_tasks || '</strong><br>Overdue</td>' ||

            '</tr></table>' ||

            '<h3 style="margin:0 0 10px">Not Started or In Progress With Due Dates</h3>';


        for r in (

            select v.task_id,

                   v.task_key,

                   v.title,

                   v.status_code,

                   v.status_name,

                   v.priority_code,

                   v.due_date,

                   v.overdue_yn,

                   v.application_name,

                   v.type_name,

                   v.complexity_name,

                   v.percent_complete,

                   regexp_replace(dbms_lob.substr(t.description, 500, 1), '<[^>]+>', ' ') as description_text,

                   (

                       select regexp_replace(dbms_lob.substr(tu.update_text, 500, 1), '<[^>]+>', ' ')

                         from tsk_task_updates tu

                        where tu.task_id = v.task_id

                        order by tu.created_at desc

                        fetch first 1 row only

                   ) as last_update

              from tsk_v_task_list v

              join tsk_tasks t

                on t.task_id = v.task_id

              join tsk_task_assignees ta

                on ta.task_id = v.task_id

               and ta.active_yn = 'Y'

             where ta.team_member_id = p_team_member_id

               and v.status_code in ('NOT_STARTED', 'IN_PROGRESS')

               and v.due_date is not null

             order by case when v.overdue_yn = 'Y' then 0 else 1 end,

                      case upper(v.priority_code)

                          when 'CRITICAL' then 1

                          when 'HIGH' then 2

                          when 'MEDIUM' then 3

                          when 'LOW' then 4

                          else 5

                      end,

                      v.due_date nulls last,

                      v.task_key

             fetch first 15 rows only

        ) loop

            l_has_due_tasks := true;

            l_html := l_html ||

                '<div style="border:1px solid #d8dee8;border-radius:6px;padding:12px;margin:0 0 10px">' ||

                '<div style="font-size:15px;font-weight:700;margin-bottom:4px">' ||

                '<a style="color:#0f62fe;text-decoration:none" href="' ||

                html_href(task_url(r.task_id)) || '">' ||

                apex_escape.html(r.task_key) || '</a> ' ||

                apex_escape.html(r.title) ||

                '</div>' ||

                '<div style="color:#5f6b7a;margin-bottom:8px">' ||

                apex_escape.html(r.priority_code) || ' priority &#8226; ' ||

                apex_escape.html(r.status_name) || ' &#8226; Due ' ||

                coalesce(to_char(r.due_date, 'Mon DD, YYYY'), 'No due date') ||

                case when r.overdue_yn = 'Y' then ' <span style="color:#b42318;font-weight:700">(Overdue)</span>' end ||

                '</div>' ||

                '<div style="margin-bottom:6px">' ||

                '<strong>Application:</strong> ' || apex_escape.html(coalesce(r.application_name, 'Unassigned')) ||

                ' &#8226; <strong>Type:</strong> ' || apex_escape.html(r.type_name) ||

                ' &#8226; <strong>Complexity:</strong> ' || apex_escape.html(coalesce(r.complexity_name, 'Not set')) ||

                ' &#8226; <strong>Complete:</strong> ' || r.percent_complete || '%' ||

                '</div>';


            if r.description_text is not null then

                l_html := l_html ||

                    '<div style="color:#344054;margin-bottom:6px"><strong>Details:</strong> ' ||

                    apex_escape.html(r.description_text) || '</div>';

            end if;


            if r.last_update is not null then

                l_html := l_html ||

                    '<div style="color:#344054"><strong>Last update:</strong> ' ||

                    apex_escape.html(r.last_update) || '</div>';

            end if;


            l_html := l_html || '</div>';

        end loop;


        if not l_has_due_tasks then

            l_html := l_html ||

                '<div style="border:1px solid #d8dee8;border-radius:6px;padding:12px">' ||

                'No not started or in progress assigned tasks have due dates.</div>';

        end if;


        l_html := l_html ||

            '<h3 style="margin:18px 0 10px">Not Started or In Progress Without Due Dates</h3>';


        for r in (

            select v.task_id,

                   v.task_key,

                   v.title,

                   v.status_code,

                   v.status_name,

                   v.priority_code,

                   v.due_date,

                   v.overdue_yn,

                   v.application_name,

                   v.type_name,

                   v.complexity_name,

                   v.percent_complete,

                   regexp_replace(dbms_lob.substr(t.description, 500, 1), '<[^>]+>', ' ') as description_text,

                   (

                       select regexp_replace(dbms_lob.substr(tu.update_text, 500, 1), '<[^>]+>', ' ')

                         from tsk_task_updates tu

                        where tu.task_id = v.task_id

                        order by tu.created_at desc

                        fetch first 1 row only

                   ) as last_update

              from tsk_v_task_list v

              join tsk_tasks t

                on t.task_id = v.task_id

              join tsk_task_assignees ta

                on ta.task_id = v.task_id

               and ta.active_yn = 'Y'

             where ta.team_member_id = p_team_member_id

               and v.status_code in ('NOT_STARTED', 'IN_PROGRESS')

               and v.due_date is null

             order by case upper(v.priority_code)

                          when 'CRITICAL' then 1

                          when 'HIGH' then 2

                          when 'MEDIUM' then 3

                          when 'LOW' then 4

                          else 5

                      end,

                      v.task_key

             fetch first 15 rows only

        ) loop

            l_has_missing_due_tasks := true;

            l_html := l_html ||

                '<div style="border:1px solid #d8dee8;border-radius:6px;padding:12px;margin:0 0 10px">' ||

                '<div style="font-size:15px;font-weight:700;margin-bottom:4px">' ||

                '<a style="color:#0f62fe;text-decoration:none" href="' ||

                html_href(task_url(r.task_id)) || '">' ||

                apex_escape.html(r.task_key) || '</a> ' ||

                apex_escape.html(r.title) ||

                '</div>' ||

                '<div style="color:#5f6b7a;margin-bottom:8px">' ||

                apex_escape.html(r.priority_code) || ' priority &#8226; ' ||

                apex_escape.html(r.status_name) || ' &#8226; ' ||

                '<span style="color:#b42318;font-weight:700">No due date</span>' ||

                '</div>' ||

                '<div style="margin-bottom:6px">' ||

                '<strong>Application:</strong> ' || apex_escape.html(coalesce(r.application_name, 'Unassigned')) ||

                ' &#8226; <strong>Type:</strong> ' || apex_escape.html(r.type_name) ||

                ' &#8226; <strong>Complexity:</strong> ' || apex_escape.html(coalesce(r.complexity_name, 'Not set')) ||

                ' &#8226; <strong>Complete:</strong> ' || r.percent_complete || '%' ||

                '</div>';


            if r.description_text is not null then

                l_html := l_html ||

                    '<div style="color:#344054;margin-bottom:6px"><strong>Details:</strong> ' ||

                    apex_escape.html(r.description_text) || '</div>';

            end if;


            if r.last_update is not null then

                l_html := l_html ||

                    '<div style="color:#344054"><strong>Last update:</strong> ' ||

                    apex_escape.html(r.last_update) || '</div>';

            end if;


            l_html := l_html || '</div>';

        end loop;


        if not l_has_missing_due_tasks then

            l_html := l_html ||

                '<div style="border:1px solid #d8dee8;border-radius:6px;padding:12px">' ||

                'No not started or in progress assigned tasks are missing due dates.</div>';

        end if;


        return l_html ||

            '<div style="color:#5f6b7a;margin-top:18px;font-size:12px">Generated by Task Center.</div>' ||

            '</div>';

    exception

        when no_data_found then

            return '<div>No active team member was found for this preview.</div>';

    end member_email_html;


    function monthly_team_subject (

        p_team_id  in number,

        p_run_date in date default trunc(sysdate)

    ) return varchar2 is

        l_team_name tsk_teams.team_name%type;

    begin

        select team_name

          into l_team_name

          from tsk_teams

         where team_id = p_team_id;


        return 'Monthly Team Progress for ' || l_team_name || ' - ' ||

               to_char(add_months(trunc(p_run_date, 'MM'), -1), 'Month YYYY');

    exception

        when no_data_found then

            return 'Monthly Team Progress - ' ||

                   to_char(add_months(trunc(p_run_date, 'MM'), -1), 'Month YYYY');

    end monthly_team_subject;


    function monthly_team_html (

        p_team_id  in number,

        p_run_date in date default trunc(sysdate)

    ) return clob is

        l_html            clob;

        l_team_name       tsk_teams.team_name%type;

        l_period_start    date := add_months(trunc(p_run_date, 'MM'), -1);

        l_period_end      date := trunc(p_run_date, 'MM');

        l_total_tasks     number;

        l_created_month   number;

        l_completed_month number;

        l_open_tasks      number;

        l_overdue_tasks   number;

        l_avg_complete    number;

    begin

        set_apex_context;


        select team_name

          into l_team_name

          from tsk_teams

         where team_id = p_team_id;


        select count(*),

               sum(case when t.created_at >= cast(l_period_start as timestamp)

                         and t.created_at < cast(l_period_end as timestamp) then 1 else 0 end),

               sum(case when t.completed_date >= l_period_start

                         and t.completed_date < l_period_end then 1 else 0 end),

               sum(case when nvl(st.is_done_yn, 'N') = 'N' then 1 else 0 end),

               sum(case when t.due_date < trunc(sysdate)

                         and nvl(st.is_done_yn, 'N') = 'N' then 1 else 0 end),

               round(avg(t.percent_complete))

          into l_total_tasks,

               l_created_month,

               l_completed_month,

               l_open_tasks,

               l_overdue_tasks,

               l_avg_complete

          from tsk_tasks t

          left join tsk_statuses st

            on st.status_id = t.status_id

         where t.team_id = p_team_id;


        l_html :=

            '<div style="font-family:Arial,sans-serif;color:#172033;line-height:1.45">' ||

            '<h2 style="margin:0 0 4px">Monthly Team Progress</h2>' ||

            '<div style="color:#5f6b7a;margin-bottom:18px">' ||

            apex_escape.html(l_team_name) || ' &#8226; ' ||

            to_char(l_period_start, 'Mon DD, YYYY') || ' - ' ||

            to_char(l_period_end - 1, 'Mon DD, YYYY') ||

            '</div>' ||

            '<table role="presentation" style="border-collapse:collapse;margin-bottom:18px;width:100%"><tr>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong>' || l_total_tasks || '</strong><br>Total Tasks</td>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong>' || l_created_month || '</strong><br>Created</td>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong>' || l_completed_month || '</strong><br>Completed</td>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong>' || l_open_tasks || '</strong><br>Open</td>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong style="color:#b42318">' || l_overdue_tasks || '</strong><br>Overdue</td>' ||

            '<td style="padding:10px;border:1px solid #d8dee8"><strong>' || nvl(l_avg_complete, 0) || '%</strong><br>Avg Complete</td>' ||

            '</tr></table>' ||

            '<h3 style="margin:0 0 10px">Progress by Status</h3>' ||

            '<table style="border-collapse:collapse;width:100%;margin-bottom:18px">' ||

            '<tr><th align="left" style="border-bottom:1px solid #d8dee8;padding:8px">Status</th>' ||

            '<th align="right" style="border-bottom:1px solid #d8dee8;padding:8px">Tasks</th></tr>';


        for r in (

            select nvl(st.status_name, 'No Status') status_name,

                   count(*) task_count

              from tsk_tasks t

              left join tsk_statuses st

                on st.status_id = t.status_id

             where t.team_id = p_team_id

             group by nvl(st.status_name, 'No Status'), nvl(st.display_seq, 999)

             order by nvl(st.display_seq, 999), nvl(st.status_name, 'No Status')

        ) loop

            l_html := l_html ||

                '<tr><td style="border-bottom:1px solid #eef2f7;padding:8px">' ||

                apex_escape.html(r.status_name) ||

                '</td><td align="right" style="border-bottom:1px solid #eef2f7;padding:8px">' ||

                r.task_count || '</td></tr>';

        end loop;


        l_html := l_html ||

            '</table><h3 style="margin:0 0 10px">Progress by Team Member</h3>' ||

            '<table style="border-collapse:collapse;width:100%;margin-bottom:18px">' ||

            '<tr><th align="left" style="border-bottom:1px solid #d8dee8;padding:8px">Team Member</th>' ||

            '<th align="right" style="border-bottom:1px solid #d8dee8;padding:8px">Open</th>' ||

            '<th align="right" style="border-bottom:1px solid #d8dee8;padding:8px">Completed This Month</th>' ||

            '<th align="right" style="border-bottom:1px solid #d8dee8;padding:8px">Overdue</th></tr>';


        for r in (

            select u.display_name,

                   count(distinct case when nvl(st.is_done_yn, 'N') = 'N' then t.task_id end) open_tasks,

                   count(distinct case when t.completed_date >= l_period_start

                                         and t.completed_date < l_period_end then t.task_id end) completed_month,

                   count(distinct case when t.due_date < trunc(sysdate)

                                         and nvl(st.is_done_yn, 'N') = 'N' then t.task_id end) overdue_tasks

              from tsk_team_members tm

              join tsk_users u

                on u.user_id = tm.user_id

              left join tsk_task_assignees ta

                on ta.team_member_id = tm.team_member_id

               and ta.active_yn = 'Y'

              left join tsk_tasks t

                on t.task_id = ta.task_id

              left join tsk_statuses st

                on st.status_id = t.status_id

             where tm.team_id = p_team_id

               and tm.active_yn = 'Y'

               and u.active_yn = 'Y'

             group by u.display_name

             order by u.display_name

        ) loop

            l_html := l_html ||

                '<tr><td style="border-bottom:1px solid #eef2f7;padding:8px">' ||

                apex_escape.html(r.display_name) ||

                '</td><td align="right" style="border-bottom:1px solid #eef2f7;padding:8px">' ||

                r.open_tasks ||

                '</td><td align="right" style="border-bottom:1px solid #eef2f7;padding:8px">' ||

                r.completed_month ||

                '</td><td align="right" style="border-bottom:1px solid #eef2f7;padding:8px;color:#b42318">' ||

                r.overdue_tasks || '</td></tr>';

        end loop;


        l_html := l_html ||

            '</table><h3 style="margin:0 0 10px">Tasks by Application</h3>' ||

            '<table style="border-collapse:collapse;width:100%">' ||

            '<tr><th align="left" style="border-bottom:1px solid #d8dee8;padding:8px">Application</th>' ||

            '<th align="right" style="border-bottom:1px solid #d8dee8;padding:8px">Open</th>' ||

            '<th align="right" style="border-bottom:1px solid #d8dee8;padding:8px">Completed This Month</th></tr>';


        for r in (

            select nvl(a.application_name, 'Unassigned') application_name,

                   count(case when nvl(st.is_done_yn, 'N') = 'N' then 1 end) open_tasks,

                   count(case when t.completed_date >= l_period_start

                                and t.completed_date < l_period_end then 1 end) completed_month

              from tsk_tasks t

              left join tsk_applications a

                on a.application_id = t.application_id

              left join tsk_statuses st

                on st.status_id = t.status_id

             where t.team_id = p_team_id

             group by nvl(a.application_name, 'Unassigned')

             order by nvl(a.application_name, 'Unassigned')

        ) loop

            l_html := l_html ||

                '<tr><td style="border-bottom:1px solid #eef2f7;padding:8px">' ||

                apex_escape.html(r.application_name) ||

                '</td><td align="right" style="border-bottom:1px solid #eef2f7;padding:8px">' ||

                r.open_tasks ||

                '</td><td align="right" style="border-bottom:1px solid #eef2f7;padding:8px">' ||

                r.completed_month || '</td></tr>';

        end loop;


        return l_html ||

            '</table><div style="color:#5f6b7a;margin-top:18px;font-size:12px">Generated by Task Center.</div>' ||

            '</div>';

    exception

        when no_data_found then

            return '<div>No active team was found for this preview.</div>';

    end monthly_team_html;


    procedure queue_daily_schedule (

        p_email_schedule_id in number

    ) is

        l_subject varchar2(500);

        l_body    clob;

        l_error   varchar2(4000);

    begin

        for s in (

            select email_schedule_id,

                   team_id

              from tsk_email_schedules

             where email_schedule_id = p_email_schedule_id

               and schedule_code = 'DAILY_MEMBER_STATUS'

        ) loop

            for m in (

                select tm.team_member_id,

                       u.email

                  from tsk_team_members tm

                  join tsk_users u

                    on u.user_id = tm.user_id

                 where tm.team_id = s.team_id

                   and tm.active_yn = 'Y'

                   and u.active_yn = 'Y'

                   and u.email is not null

                   and (

                           not exists (

                               select 1

                                 from tsk_email_recipients er

                                where er.email_schedule_id = s.email_schedule_id

                                  and er.active_yn = 'Y'

                                  and er.team_member_id is not null

                           )

                        or exists (

                                   select 1

                                     from tsk_email_recipients er

                                    where er.email_schedule_id = s.email_schedule_id

                                      and er.team_member_id = tm.team_member_id

                                      and er.active_yn = 'Y'

                               )

                       )

            ) loop

                begin

                    l_subject := member_email_subject(m.team_member_id);

                    l_body := member_email_html(m.team_member_id);


                    apex_mail.send(

                        p_to        => m.email,

                        p_from      => 'no-reply@oracle.com',

                        p_subj      => l_subject,

                        p_body      => 'Open Task Center to view your daily task summary.',

                        p_body_html => dbms_lob.substr(l_body, 32767, 1)

                    );


                    insert into tsk_email_log (

                        email_schedule_id,

                        team_id,

                        team_member_id,

                        recipient_email,

                        email_subject,

                        email_body,

                        status_code,

                        run_period_start,

                        run_period_end

                    ) values (

                        s.email_schedule_id,

                        s.team_id,

                        m.team_member_id,

                        m.email,

                        l_subject,

                        l_body,

                        'QUEUED',

                        trunc(sysdate),

                        trunc(sysdate) + 1 - (1 / 86400)

                    );

                exception

                    when others then

                        l_error := sqlerrm;

                        insert into tsk_email_log (

                            email_schedule_id,

                            team_id,

                            team_member_id,

                            recipient_email,

                            email_subject,

                            email_body,

                            status_code,

                            run_period_start,

                            run_period_end,

                            error_message

                        ) values (

                            s.email_schedule_id,

                            s.team_id,

                            m.team_member_id,

                            m.email,

                            l_subject,

                            l_body,

                            'FAILED',

                            trunc(sysdate),

                            trunc(sysdate) + 1 - (1 / 86400),

                            l_error

                        );

                end;

            end loop;

        end loop;


    end queue_daily_schedule;


    procedure send_daily_schedule (

        p_email_schedule_id in number

    ) is

    begin

        set_apex_context;

        queue_daily_schedule(p_email_schedule_id);

        apex_mail.push_queue;

        commit;

    end send_daily_schedule;


    procedure send_daily_summaries is

    begin

        set_apex_context;


        for s in (

            select email_schedule_id

              from tsk_email_schedules

             where schedule_code = 'DAILY_MEMBER_STATUS'

               and enabled_yn = 'Y'

        ) loop

            queue_daily_schedule(s.email_schedule_id);

        end loop;


        apex_mail.push_queue;

        commit;

    end send_daily_summaries;


    procedure send_monthly_summaries is

        l_subject varchar2(500);

        l_body    clob;

        l_error   varchar2(4000);

    begin

        set_apex_context;


        for s in (

            select email_schedule_id,

                   team_id,

                   recipients_scope

              from tsk_email_schedules

             where schedule_code = 'MONTHLY_TEAM_PROGRESS'

               and enabled_yn = 'Y'

        ) loop

            l_subject := monthly_team_subject(s.team_id);

            l_body := monthly_team_html(s.team_id);


            for m in (

                select tm.team_member_id,

                       u.email

                  from tsk_team_members tm

                  join tsk_users u

                    on u.user_id = tm.user_id

                 where tm.team_id = s.team_id

                   and tm.active_yn = 'Y'

                   and u.active_yn = 'Y'

                   and u.email is not null

                   and (

                           s.recipients_scope = 'TEAM_MEMBERS'

                        or (s.recipients_scope = 'TEAM_LEADS' and upper(nvl(tm.role_name, '')) like '%LEAD%')

                        or (s.recipients_scope = 'MANAGERS' and upper(nvl(tm.role_name, '')) like '%MANAGER%')

                        or (

                               s.recipients_scope = 'CUSTOM'

                           and exists (

                                   select 1

                                     from tsk_email_recipients er

                                    where er.email_schedule_id = s.email_schedule_id

                                      and er.team_member_id = tm.team_member_id

                                      and er.active_yn = 'Y'

                               )

                           )

                       )

            ) loop

                begin

                    apex_mail.send(

                        p_to        => m.email,

                        p_from      => 'no-reply@oracle.com',

                        p_subj      => l_subject,

                        p_body      => 'Open Task Center to view your monthly team progress summary.',

                        p_body_html => dbms_lob.substr(l_body, 32767, 1)

                    );


                    insert into tsk_email_log (

                        email_schedule_id,

                        team_id,

                        team_member_id,

                        recipient_email,

                        email_subject,

                        email_body,

                        status_code,

                        run_period_start,

                        run_period_end

                    ) values (

                        s.email_schedule_id,

                        s.team_id,

                        m.team_member_id,

                        m.email,

                        l_subject,

                        l_body,

                        'QUEUED',

                        add_months(trunc(sysdate, 'MM'), -1),

                        trunc(sysdate, 'MM') - (1 / 86400)

                    );

                exception

                    when others then

                        l_error := sqlerrm;

                        insert into tsk_email_log (

                            email_schedule_id,

                            team_id,

                            team_member_id,

                            recipient_email,

                            email_subject,

                            email_body,

                            status_code,

                            run_period_start,

                            run_period_end,

                            error_message

                        ) values (

                            s.email_schedule_id,

                            s.team_id,

                            m.team_member_id,

                            m.email,

                            l_subject,

                            l_body,

                            'FAILED',

                            add_months(trunc(sysdate, 'MM'), -1),

                            trunc(sysdate, 'MM') - (1 / 86400),

                            l_error

                        );

                end;

            end loop;

        end loop;


        apex_mail.push_queue;

        commit;

    end send_monthly_summaries;


    procedure sync_scheduler_jobs is
    begin
        null;
    end sync_scheduler_jobs;

end tsk_daily_email_pkg;

/
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_CHANGE_LOG" ("CHANGE_ID", "ENTITY_NAME", "ENTITY_PK", "TASK_ID", "TASK_KEY", "TASK_TITLE", "CHANGE_ACTION", "FIELD_NAME", "OLD_VALUE", "NEW_VALUE", "CHANGE_NOTE", "CHANGED_AT", "CHANGED_BY") AS
  select
    cl.change_id,
    cl.entity_name,
    cl.entity_pk,
    cl.task_id,
    t.task_key,
    t.title as task_title,
    cl.change_action,
    cl.field_name,
    cl.old_value,
    cl.new_value,
    cl.change_note,
    cl.changed_at,
    cl.changed_by
from tsk_change_log cl
left join tsk_tasks t
    on t.task_id = cl.task_id;
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_DAILY_MEMBER_EMAIL" ("TEAM_ID", "TEAM_NAME", "TEAM_MEMBER_ID", "DISPLAY_NAME", "EMAIL", "OPEN_TASKS", "IN_PROGRESS_TASKS", "IN_REVIEW_TASKS", "BLOCKED_TASKS", "COMPLETED_TASKS", "OVERDUE_TASKS", "DUE_TODAY_TASKS", "UPDATES_TODAY", "OPEN_TASK_SUMMARY") AS
  select
    tm.team_id,
    team.team_name,
    tm.team_member_id,
    u.display_name,
    u.email,
    count(distinct case when st.is_done_yn = 'N' then t.task_id end) as open_tasks,
    count(distinct case when st.status_code = 'IN_PROGRESS' then t.task_id end) as in_progress_tasks,
    count(distinct case when st.status_code = 'IN_REVIEW' then t.task_id end) as in_review_tasks,
    count(distinct case when st.status_code = 'BLOCKED' then t.task_id end) as blocked_tasks,
    count(distinct case when st.is_done_yn = 'Y' then t.task_id end) as completed_tasks,
    count(
        distinct case
            when t.due_date < trunc(sysdate)
             and st.is_done_yn = 'N'
            then t.task_id
        end
    ) as overdue_tasks,
    count(
        distinct case
            when t.due_date = trunc(sysdate)
             and st.is_done_yn = 'N'
            then t.task_id
        end
    ) as due_today_tasks,
    (
        select count(*)
        from tsk_task_updates upd
        join tsk_task_assignees ta2
            on ta2.task_id = upd.task_id
           and ta2.team_member_id = tm.team_member_id
           and ta2.active_yn = 'Y'
        where upd.created_at >= cast(trunc(sysdate) as timestamp)
          and upd.created_at <  cast(trunc(sysdate + 1) as timestamp)
    ) as updates_today,
    listagg(
        case
            when st.is_done_yn = 'N' then
                t.task_key || ' - ' || t.title || ' [' || st.status_name || '] due ' ||
                coalesce(to_char(t.due_date, 'YYYY-MM-DD'), 'No due date')
        end,
        chr(10)
    ) within group (order by t.due_date nulls last, t.task_key) as open_task_summary
from tsk_team_members tm
join tsk_teams team
    on team.team_id = tm.team_id
join tsk_users u
    on u.user_id = tm.user_id
left join tsk_task_assignees ta
    on ta.team_member_id = tm.team_member_id
   and ta.active_yn = 'Y'
left join tsk_tasks t
    on t.task_id = ta.task_id
left join tsk_statuses st
    on st.status_id = t.status_id
where tm.active_yn = 'Y'
  and u.active_yn = 'Y'
group by
    tm.team_id,
    team.team_name,
    tm.team_member_id,
    u.display_name,
    u.email;
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_DASHBOARD_SUMMARY" ("TEAM_ID", "TEAM_NAME", "TOTAL_TASKS", "IN_PROGRESS_TASKS", "COMPLETED_TASKS", "OVERDUE_TASKS", "BLOCKED_TASKS", "AVG_PERCENT_COMPLETE") AS
  select
    tm.team_id,
    tm.team_name,
    count(t.task_id) as total_tasks,
    sum(case when st.status_code = 'IN_PROGRESS' then 1 else 0 end) as in_progress_tasks,
    sum(case when st.is_done_yn = 'Y' then 1 else 0 end) as completed_tasks,
    sum(
        case
            when t.due_date < trunc(sysdate)
             and st.is_done_yn = 'N'
            then 1
            else 0
        end
    ) as overdue_tasks,
    sum(case when st.status_code = 'BLOCKED' then 1 else 0 end) as blocked_tasks,
    round(avg(t.percent_complete), 1) as avg_percent_complete
from tsk_teams tm
left join tsk_tasks t
    on t.team_id = tm.team_id
left join tsk_statuses st
    on st.status_id = t.status_id
group by
    tm.team_id,
    tm.team_name;
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_OVERDUE_TASKS" ("TASK_ID", "TASK_KEY", "TEAM_ID", "TEAM_NAME", "TITLE", "TYPE_CODE", "TYPE_NAME", "APPLICATION_CODE", "APPLICATION_NAME", "COMPLEXITY_CODE", "COMPLEXITY_NAME", "COMPLEXITY_WEIGHT", "STATUS_CODE", "STATUS_NAME", "IS_OPEN_YN", "IS_DONE_YN", "PRIORITY_CODE", "START_DATE", "DUE_DATE", "COMPLETED_DATE", "ESTIMATED_HOURS", "ACTUAL_HOURS", "PERCENT_COMPLETE", "OVERDUE_YN", "ASSIGNEES", "ACTIVE_ASSIGNEE_COUNT", "CREATED_AT", "UPDATED_AT") AS
  select "TASK_ID","TASK_KEY","TEAM_ID","TEAM_NAME","TITLE","TYPE_CODE","TYPE_NAME","APPLICATION_CODE","APPLICATION_NAME","COMPLEXITY_CODE","COMPLEXITY_NAME","COMPLEXITY_WEIGHT","STATUS_CODE","STATUS_NAME","IS_OPEN_YN","IS_DONE_YN","PRIORITY_CODE","START_DATE","DUE_DATE","COMPLETED_DATE","ESTIMATED_HOURS","ACTUAL_HOURS","PERCENT_COMPLETE","OVERDUE_YN","ASSIGNEES","ACTIVE_ASSIGNEE_COUNT","CREATED_AT","UPDATED_AT"
from tsk_v_task_list
where overdue_yn = 'Y';
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_TASKS_BY_APPLICATION" ("TEAM_ID", "TEAM_NAME", "APPLICATION_ID", "APPLICATION_CODE", "APPLICATION_NAME", "TASK_COUNT") AS
  select
    t.team_id,
    tm.team_name,
    app.application_id,
    app.application_code,
    app.application_name,
    count(t.task_id) as task_count
from tsk_tasks t
join tsk_teams tm
    on tm.team_id = t.team_id
left join tsk_applications app
    on app.application_id = t.application_id
group by
    t.team_id,
    tm.team_name,
    app.application_id,
    app.application_code,
    app.application_name;
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_TASKS_BY_STATUS" ("TEAM_ID", "TEAM_NAME", "STATUS_ID", "STATUS_CODE", "STATUS_NAME", "DISPLAY_SEQ", "TASK_COUNT") AS
  select
    tm.team_id,
    tm.team_name,
    st.status_id,
    st.status_code,
    st.status_name,
    st.display_seq,
    count(t.task_id) as task_count
from tsk_teams tm
cross join tsk_statuses st
left join tsk_tasks t
    on t.team_id = tm.team_id
   and t.status_id = st.status_id
where st.active_yn = 'Y'
group by
    tm.team_id,
    tm.team_name,
    st.status_id,
    st.status_code,
    st.status_name,
    st.display_seq;
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_TASKS_BY_TYPE" ("TEAM_ID", "TEAM_NAME", "TYPE_ID", "TYPE_CODE", "TYPE_NAME", "DISPLAY_SEQ", "TASK_COUNT") AS
  select
    tm.team_id,
    tm.team_name,
    ty.type_id,
    ty.type_code,
    ty.type_name,
    ty.display_seq,
    count(t.task_id) as task_count
from tsk_teams tm
cross join tsk_task_types ty
left join tsk_tasks t
    on t.team_id = tm.team_id
   and t.type_id = ty.type_id
where ty.active_yn = 'Y'
group by
    tm.team_id,
    tm.team_name,
    ty.type_id,
    ty.type_code,
    ty.type_name,
    ty.display_seq;
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_TASK_LIST" ("TASK_ID", "TASK_KEY", "TEAM_ID", "TEAM_NAME", "TITLE", "TYPE_CODE", "TYPE_NAME", "APPLICATION_CODE", "APPLICATION_NAME", "COMPLEXITY_CODE", "COMPLEXITY_NAME", "COMPLEXITY_WEIGHT", "STATUS_CODE", "STATUS_NAME", "IS_OPEN_YN", "IS_DONE_YN", "PRIORITY_CODE", "START_DATE", "DUE_DATE", "COMPLETED_DATE", "ESTIMATED_HOURS", "ACTUAL_HOURS", "PERCENT_COMPLETE", "OVERDUE_YN", "ASSIGNEES", "ACTIVE_ASSIGNEE_COUNT", "CREATED_AT", "UPDATED_AT") AS
  select
    t.task_id,
    t.task_key,
    t.team_id,
    tm.team_name,
    t.title,
    ty.type_code,
    ty.type_name,
    app.application_code,
    app.application_name,
    cx.complexity_code,
    cx.complexity_name,
    cx.complexity_weight,
    st.status_code,
    st.status_name,
    st.is_open_yn,
    st.is_done_yn,
    t.priority_code,
    t.start_date,
    t.due_date,
    t.completed_date,
    t.estimated_hours,
    t.actual_hours,
    t.percent_complete,
    case
        when t.due_date < trunc(sysdate)
         and st.is_done_yn = 'N'
        then 'Y'
        else 'N'
    end as overdue_yn,
    listagg(u.display_name, ', ')
        within group (order by u.display_name) as assignees,
    count(u.user_id) as active_assignee_count,
    t.created_at,
    t.updated_at
from tsk_tasks t
join tsk_teams tm
    on tm.team_id = t.team_id
join tsk_task_types ty
    on ty.type_id = t.type_id
left join tsk_applications app
    on app.application_id = t.application_id
left join tsk_complexities cx
    on cx.complexity_id = t.complexity_id
left join tsk_statuses st
    on st.status_id = t.status_id
left join tsk_task_assignees ta
    on ta.task_id = t.task_id
   and ta.active_yn = 'Y'
left join tsk_team_members tmem
    on tmem.team_member_id = ta.team_member_id
left join tsk_users u
    on u.user_id = tmem.user_id
group by
    t.task_id,
    t.task_key,
    t.team_id,
    tm.team_name,
    t.title,
    ty.type_code,
    ty.type_name,
    app.application_code,
    app.application_name,
    cx.complexity_code,
    cx.complexity_name,
    cx.complexity_weight,
    st.status_code,
    st.status_name,
    st.is_open_yn,
    st.is_done_yn,
    t.priority_code,
    t.start_date,
    t.due_date,
    t.completed_date,
    t.estimated_hours,
    t.actual_hours,
    t.percent_complete,
    t.created_at,
    t.updated_at;
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_TEAM_MEMBER_WORKLOAD" ("TEAM_ID", "TEAM_NAME", "TEAM_MEMBER_ID", "USER_ID", "DISPLAY_NAME", "EMAIL", "ROLE_NAME", "MEMBER_ACTIVE_YN", "ASSIGNED_TASKS", "NOT_STARTED_TASKS", "IN_PROGRESS_TASKS", "IN_REVIEW_TASKS", "BLOCKED_TASKS", "COMPLETED_TASKS", "OVERDUE_TASKS", "AVG_PERCENT_COMPLETE") AS
  select
    tm.team_id,
    team.team_name,
    tm.team_member_id,
    u.user_id,
    u.display_name,
    u.email,
    tm.role_name,
    tm.active_yn as member_active_yn,
    count(distinct t.task_id) as assigned_tasks,
    sum(case when st.status_code = 'NOT_STARTED' then 1 else 0 end) as not_started_tasks,
    sum(case when st.status_code = 'IN_PROGRESS' then 1 else 0 end) as in_progress_tasks,
    sum(case when st.status_code = 'IN_REVIEW' then 1 else 0 end) as in_review_tasks,
    sum(case when st.status_code = 'BLOCKED' then 1 else 0 end) as blocked_tasks,
    sum(case when st.is_done_yn = 'Y' then 1 else 0 end) as completed_tasks,
    sum(
        case
            when t.due_date < trunc(sysdate)
             and st.is_done_yn = 'N'
            then 1
            else 0
        end
    ) as overdue_tasks,
    round(avg(t.percent_complete), 1) as avg_percent_complete
from tsk_team_members tm
join tsk_teams team
    on team.team_id = tm.team_id
join tsk_users u
    on u.user_id = tm.user_id
left join tsk_task_assignees ta
    on ta.team_member_id = tm.team_member_id
   and ta.active_yn = 'Y'
left join tsk_tasks t
    on t.task_id = ta.task_id
left join tsk_statuses st
    on st.status_id = t.status_id
group by
    tm.team_id,
    team.team_name,
    tm.team_member_id,
    u.user_id,
    u.display_name,
    u.email,
    tm.role_name,
    tm.active_yn;
/


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TSK_V_WEEKLY_TEAM_EMAIL" ("TEAM_ID", "TEAM_NAME", "WEEK_START_DATE", "WEEK_END_DATE", "TOTAL_TASKS", "TASKS_CREATED_THIS_WEEK", "TASKS_COMPLETED_THIS_WEEK", "OPEN_TASKS", "IN_PROGRESS_TASKS", "IN_REVIEW_TASKS", "BLOCKED_TASKS", "COMPLETED_TASKS", "OVERDUE_TASKS", "UPCOMING_DUE_TASKS") AS
  select
    team.team_id,
    team.team_name,
    trunc(sysdate, 'IW') as week_start_date,
    trunc(sysdate, 'IW') + 6 as week_end_date,
    count(t.task_id) as total_tasks,
    count(
        case
            when t.created_at >= cast(trunc(sysdate, 'IW') as timestamp)
            then t.task_id
        end
    ) as tasks_created_this_week,
    count(
        case
            when t.completed_date between trunc(sysdate, 'IW') and trunc(sysdate, 'IW') + 6
            then t.task_id
        end
    ) as tasks_completed_this_week,
    sum(case when st.is_done_yn = 'N' then 1 else 0 end) as open_tasks,
    sum(case when st.status_code = 'IN_PROGRESS' then 1 else 0 end) as in_progress_tasks,
    sum(case when st.status_code = 'IN_REVIEW' then 1 else 0 end) as in_review_tasks,
    sum(case when st.status_code = 'BLOCKED' then 1 else 0 end) as blocked_tasks,
    sum(case when st.is_done_yn = 'Y' then 1 else 0 end) as completed_tasks,
    sum(
        case
            when t.due_date < trunc(sysdate)
             and st.is_done_yn = 'N'
            then 1
            else 0
        end
    ) as overdue_tasks,
    listagg(
        case
            when t.due_date between trunc(sysdate) and trunc(sysdate) + 7
             and st.is_done_yn = 'N'
            then t.task_key || ' - ' || t.title || ' due ' || to_char(t.due_date, 'YYYY-MM-DD')
        end,
        chr(10)
    ) within group (order by t.due_date nulls last, t.task_key) as upcoming_due_tasks
from tsk_teams team
left join tsk_tasks t
    on t.team_id = team.team_id
left join tsk_statuses st
    on st.status_id = t.status_id
group by
    team.team_id,
    team.team_name;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TASKS_AUD"
after insert or update or delete on tsk_tasks
for each row
declare
    procedure log_change (
        p_entity_pk     in varchar2,
        p_task_id       in number,
        p_action        in varchar2,
        p_field_name    in varchar2,
        p_old_value     in varchar2,
        p_new_value     in varchar2,
        p_change_note   in varchar2
    )
    is
    begin
        insert into tsk_change_log (
            entity_name,
            entity_pk,
            task_id,
            change_action,
            field_name,
            old_value,
            new_value,
            change_note,
            changed_by
        )
        values (
            'TASK',
            p_entity_pk,
            p_task_id,
            p_action,
            p_field_name,
            p_old_value,
            p_new_value,
            p_change_note,
            tsk_app_user()
        );
    end;
begin
    if inserting then
        log_change(
            to_char(:new.task_id),
            :new.task_id,
            'INSERT',
            null,
            null,
            null,
            'Task created'
        );

    elsif deleting then
        log_change(
            to_char(:old.task_id),
            :old.task_id,
            'DELETE',
            null,
            null,
            null,
            'Task deleted'
        );

    elsif updating then

        if nvl(:old.title, chr(0)) <> nvl(:new.title, chr(0)) then
            log_change(to_char(:new.task_id), :new.task_id, 'UPDATE', 'TITLE',
                       :old.title, :new.title, null);
        end if;

        if nvl(:old.type_id, -1) <> nvl(:new.type_id, -1) then
            log_change(to_char(:new.task_id), :new.task_id, 'UPDATE', 'TYPE_ID',
                       to_char(:old.type_id), to_char(:new.type_id), null);
        end if;

        if nvl(:old.status_id, -1) <> nvl(:new.status_id, -1) then
            log_change(to_char(:new.task_id), :new.task_id, 'UPDATE', 'STATUS_ID',
                       to_char(:old.status_id), to_char(:new.status_id), null);
        end if;

        if nvl(:old.complexity_id, -1) <> nvl(:new.complexity_id, -1) then
            log_change(to_char(:new.task_id), :new.task_id, 'UPDATE', 'COMPLEXITY_ID',
                       to_char(:old.complexity_id), to_char(:new.complexity_id), null);
        end if;

        if nvl(:old.application_id, -1) <> nvl(:new.application_id, -1) then
            log_change(to_char(:new.task_id), :new.task_id, 'UPDATE', 'APPLICATION_ID',
                       to_char(:old.application_id), to_char(:new.application_id), null);
        end if;

        if nvl(:old.owner_member_id, -1) <> nvl(:new.owner_member_id, -1) then
            log_change(to_char(:new.task_id), :new.task_id, 'UPDATE', 'OWNER_MEMBER_ID',
                       to_char(:old.owner_member_id), to_char(:new.owner_member_id), null);
        end if;

        if nvl(:old.priority_code, chr(0)) <> nvl(:new.priority_code, chr(0)) then
            log_change(to_char(:new.task_id), :new.task_id, 'UPDATE', 'PRIORITY_CODE',
                       :old.priority_code, :new.priority_code, null);
        end if;

        if nvl(:old.due_date, date '1900-01-01') <>
           nvl(:new.due_date, date '1900-01-01') then
            log_change(to_char(:new.task_id), :new.task_id, 'UPDATE', 'DUE_DATE',
                       to_char(:old.due_date, 'YYYY-MM-DD'),
                       to_char(:new.due_date, 'YYYY-MM-DD'),
                       null);
        end if;

        if nvl(:old.percent_complete, -1) <> nvl(:new.percent_complete, -1) then
            log_change(to_char(:new.task_id), :new.task_id, 'UPDATE', 'PERCENT_COMPLETE',
                       to_char(:old.percent_complete),
                       to_char(:new.percent_complete),
                       null);
        end if;

    end if;
end;

/
ALTER TRIGGER "TSK_TASKS_AUD" ENABLE;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TASKS_BIU"
before insert or update on tsk_tasks
for each row
declare
    l_done_yn tsk_statuses.is_done_yn%type;
begin
    if inserting then
        :new.created_at := coalesce(:new.created_at, systimestamp);
        :new.created_by := coalesce(:new.created_by, tsk_app_user());

        if :new.status_id is null then
            select status_id
              into :new.status_id
              from tsk_statuses
             where status_code = 'NOT_STARTED';
        end if;
    end if;

    :new.updated_at := systimestamp;
    :new.updated_by := tsk_app_user();

    if :new.percent_complete is null then
        :new.percent_complete := 0;
    end if;

    if :new.status_id is not null then
        select is_done_yn
          into l_done_yn
          from tsk_statuses
         where status_id = :new.status_id;

        if l_done_yn = 'Y' then
            :new.percent_complete := 100;

            if :new.completed_date is null then
                :new.completed_date := trunc(sysdate);
            end if;
        elsif updating and nvl(:old.status_id, -1) <> nvl(:new.status_id, -1) then
            :new.completed_date := null;
        end if;
    end if;
end;

/
ALTER TRIGGER "TSK_TASKS_BIU" ENABLE;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TASK_ASSIGNEES_AUD"
after insert or update or delete on tsk_task_assignees
for each row
declare
    procedure log_change (
        p_assignment_id in number,
        p_task_id       in number,
        p_action        in varchar2,
        p_field_name    in varchar2,
        p_old_value     in varchar2,
        p_new_value     in varchar2,
        p_change_note   in varchar2
    )
    is
    begin
        insert into tsk_change_log (
            entity_name,
            entity_pk,
            task_id,
            change_action,
            field_name,
            old_value,
            new_value,
            change_note,
            changed_by
        )
        values (
            'TASK_ASSIGNMENT',
            to_char(p_assignment_id),
            p_task_id,
            p_action,
            p_field_name,
            p_old_value,
            p_new_value,
            p_change_note,
            tsk_app_user()
        );
    end;
begin
    if inserting then
        log_change(
            :new.assignment_id,
            :new.task_id,
            'ASSIGN',
            'TEAM_MEMBER_ID',
            null,
            to_char(:new.team_member_id),
            'Assignee added'
        );

    elsif deleting then
        log_change(
            :old.assignment_id,
            :old.task_id,
            'UNASSIGN',
            'TEAM_MEMBER_ID',
            to_char(:old.team_member_id),
            null,
            'Assignee removed'
        );

    elsif updating then

        if nvl(:old.team_member_id, -1) <> nvl(:new.team_member_id, -1) then
            log_change(
                :new.assignment_id,
                :new.task_id,
                'UPDATE',
                'TEAM_MEMBER_ID',
                to_char(:old.team_member_id),
                to_char(:new.team_member_id),
                null
            );
        end if;

        if nvl(:old.active_yn, chr(0)) <> nvl(:new.active_yn, chr(0)) then
            log_change(
                :new.assignment_id,
                :new.task_id,
                case when :new.active_yn = 'Y' then 'ASSIGN' else 'UNASSIGN' end,
                'ACTIVE_YN',
                :old.active_yn,
                :new.active_yn,
                case when :new.active_yn = 'Y' then 'Assignee reactivated' else 'Assignee removed from task' end
            );
        end if;

        if nvl(:old.assignment_role, chr(0)) <> nvl(:new.assignment_role, chr(0)) then
            log_change(
                :new.assignment_id,
                :new.task_id,
                'UPDATE',
                'ASSIGNMENT_ROLE',
                :old.assignment_role,
                :new.assignment_role,
                null
            );
        end if;

    end if;
end;

/
ALTER TRIGGER "TSK_TASK_ASSIGNEES_AUD" ENABLE;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TASK_ASSIGNEES_BIU"
before insert or update on tsk_task_assignees
for each row
begin
    if inserting then
        :new.created_at := coalesce(:new.created_at, systimestamp);
        :new.created_by := coalesce(:new.created_by, tsk_app_user());
        :new.assigned_on := coalesce(:new.assigned_on, trunc(sysdate));
    end if;

    :new.updated_at := systimestamp;
    :new.updated_by := tsk_app_user();

    if :new.active_yn = 'N' then
        :new.unassigned_on := coalesce(:new.unassigned_on, trunc(sysdate));
    elsif :new.active_yn = 'Y' then
        :new.unassigned_on := null;
    end if;
end;

/
ALTER TRIGGER "TSK_TASK_ASSIGNEES_BIU" ENABLE;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TASK_TOPIC_GROUPS_BI"
before insert on tsk_task_topic_groups
for each row
begin
    :new.created_at := coalesce(:new.created_at, systimestamp);
    :new.created_by := coalesce(:new.created_by, tsk_app_user());
end;

/
ALTER TRIGGER "TSK_TASK_TOPIC_GROUPS_BI" ENABLE;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TASK_UPDATES_BIU"
before insert or update on tsk_task_updates
for each row
begin
    if inserting then
        :new.created_at := coalesce(:new.created_at, systimestamp);
        :new.created_by := coalesce(:new.created_by, tsk_app_user());
        :new.updated_at := :new.created_at;
    else
        :new.updated_at := systimestamp;
    end if;
end;

/
ALTER TRIGGER "TSK_TASK_UPDATES_BIU" ENABLE;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TASK_UPDATES_AI"
after insert on tsk_task_updates
for each row
begin
    insert into tsk_change_log (
        entity_name,
        entity_pk,
        task_id,
        change_action,
        field_name,
        old_value,
        new_value,
        change_note,
        changed_by
    )
    values (
        'TASK_UPDATE',
        to_char(:new.update_id),
        :new.task_id,
        'COMMENT',
        :new.update_type,
        null,
        null,
        'Task update or comment added',
        tsk_app_user()
    );
end;

/
ALTER TRIGGER "TSK_TASK_UPDATES_AI" ENABLE;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TEAM_MEMBERS_AUD"
after update on tsk_team_members
for each row
begin
    if nvl(:old.active_yn, chr(0)) <> nvl(:new.active_yn, chr(0)) then
        insert into tsk_change_log (
            entity_name,
            entity_pk,
            task_id,
            change_action,
            field_name,
            old_value,
            new_value,
            change_note,
            changed_by
        )
        values (
            'TEAM_MEMBER',
            to_char(:new.team_member_id),
            null,
            case when :new.active_yn = 'Y' then 'REACTIVATE' else 'REMOVE' end,
            'ACTIVE_YN',
            :old.active_yn,
            :new.active_yn,
            case when :new.active_yn = 'Y' then 'Team member reactivated' else 'Team member removed from team' end,
            tsk_app_user()
        );
    end if;
end;

/
ALTER TRIGGER "TSK_TEAM_MEMBERS_AUD" ENABLE;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TEAM_MEMBERS_BIU"
before insert or update on tsk_team_members
for each row
begin
    if inserting then
        :new.created_at := coalesce(:new.created_at, systimestamp);
        :new.created_by := coalesce(:new.created_by, tsk_app_user());
        :new.joined_on := coalesce(:new.joined_on, trunc(sysdate));
    end if;

    :new.updated_at := systimestamp;
    :new.updated_by := tsk_app_user();

    if updating then
        if :old.active_yn = 'Y' and :new.active_yn = 'N' then
            :new.left_on := coalesce(:new.left_on, trunc(sysdate));
        elsif :old.active_yn = 'N' and :new.active_yn = 'Y' then
            :new.left_on := null;
        end if;
    end if;
end;

/
ALTER TRIGGER "TSK_TEAM_MEMBERS_BIU" ENABLE;
/


  CREATE OR REPLACE EDITIONABLE TRIGGER "TSK_TOPIC_GROUPS_BIU"
before insert or update on tsk_topic_groups
for each row
begin
    if inserting then
        :new.created_at := coalesce(:new.created_at, systimestamp);
        :new.created_by := coalesce(:new.created_by, tsk_app_user());
    end if;

    :new.updated_at := systimestamp;
    :new.updated_by := tsk_app_user();
end;

/
ALTER TRIGGER "TSK_TOPIC_GROUPS_BIU" ENABLE;
/

prompt Task Center schema objects installed
