set define off

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_tables
     where table_name = 'TSK_TOPIC_GROUPS';

    if l_count = 0 then
        execute immediate q'[
            create table tsk_topic_groups (
                topic_group_id number generated by default on null as identity
                    constraint tsk_topic_groups_nn01 not null,
                topic_name varchar2(200) not null,
                description varchar2(1000),
                active_yn varchar2(1) default 'Y' not null,
                created_at timestamp default systimestamp not null,
                created_by varchar2(255),
                updated_at timestamp default systimestamp not null,
                updated_by varchar2(255),
                constraint tsk_topic_groups_pk primary key (topic_group_id),
                constraint tsk_topic_groups_u01 unique (topic_name),
                constraint tsk_topic_groups_active_ck check (active_yn in ('Y','N'))
            )
        ]';
    end if;
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_tab_columns
     where table_name = 'TSK_TASKS'
       and column_name = 'TOPIC_GROUP_ID';

    if l_count = 0 then
        execute immediate 'alter table tsk_tasks add topic_group_id number';
    end if;
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_constraints
     where table_name = 'TSK_TASKS'
       and constraint_name = 'TSK_TASKS_TOPIC_GROUP_FK';

    if l_count = 0 then
        execute immediate q'[
            alter table tsk_tasks add constraint tsk_tasks_topic_group_fk
                foreign key (topic_group_id)
                references tsk_topic_groups (topic_group_id)
        ]';
    end if;
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_indexes
     where index_name = 'TSK_TASKS_I06';

    if l_count = 0 then
        execute immediate 'create index tsk_tasks_i06 on tsk_tasks (topic_group_id)';
    end if;
end;
/

create or replace trigger tsk_topic_groups_biu
before insert or update on tsk_topic_groups
for each row
begin
    if inserting then
        :new.created_at := coalesce(:new.created_at, systimestamp);
        :new.created_by := coalesce(:new.created_by, tsk_app_user());
    end if;

    :new.updated_at := systimestamp;
    :new.updated_by := tsk_app_user();
end;
/

alter trigger tsk_topic_groups_biu enable
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_tables
     where table_name = 'TSK_TASK_TOPIC_GROUPS';

    if l_count = 0 then
        execute immediate q'[
            create table tsk_task_topic_groups (
                task_topic_group_id number generated by default on null as identity
                    constraint tsk_task_topic_groups_nn01 not null,
                task_id number not null,
                topic_group_id number not null,
                created_at timestamp default systimestamp not null,
                created_by varchar2(255),
                constraint tsk_task_topic_groups_pk primary key (task_topic_group_id),
                constraint tsk_task_topic_groups_u01 unique (task_id, topic_group_id),
                constraint tsk_task_topic_groups_task_fk foreign key (task_id)
                    references tsk_tasks (task_id) on delete cascade,
                constraint tsk_task_topic_groups_topic_fk foreign key (topic_group_id)
                    references tsk_topic_groups (topic_group_id)
            )
        ]';
    end if;
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_indexes
     where index_name = 'TSK_TASK_TOPIC_GROUPS_I01';

    if l_count = 0 then
        execute immediate 'create index tsk_task_topic_groups_i01 on tsk_task_topic_groups (topic_group_id)';
    end if;
end;
/

create or replace trigger tsk_task_topic_groups_bi
before insert on tsk_task_topic_groups
for each row
begin
    :new.created_at := coalesce(:new.created_at, systimestamp);
    :new.created_by := coalesce(:new.created_by, tsk_app_user());
end;
/

alter trigger tsk_task_topic_groups_bi enable
/

insert into tsk_task_topic_groups (
    task_id,
    topic_group_id
)
select t.task_id,
       t.topic_group_id
  from tsk_tasks t
 where t.topic_group_id is not null
   and not exists (
           select 1
             from tsk_task_topic_groups ttg
            where ttg.task_id = t.task_id
              and ttg.topic_group_id = t.topic_group_id
       );
